# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Ens\JobeetBundle\Entity\User: sha512
        #Symfony\Component\Security\Core\User\User: plaintext
        
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        main:
            entity: { class: Ens\JobeetBundle\Entity\User, property: username }
        #in_memory:
         #   memory:
          #      users:
           #         admin: { password: adminpass, roles: 'ROLE_ADMIN' }

    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /login
                check_path:  /login_check
            logout:
                path:   /logout
                target: /
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
  
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
    
